apiVersion: v1
kind: Service
metadata:
  name: cloudroute-frontend
  namespace: cloudroute-lab
  labels:
    app: cloudroute-frontend
spec:
  type: ClusterIP
  selector:
    app: cloudroute-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
